spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    operationsSorter: method

api:
  security:
    token:
      secret: ${TOKEN_SECRET}

accessKey: ${ACCESS_KEY}
secretAccessKey: ${SECRET_KEY}
bucketName: ${BUCKET_NAME}