spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    operationsSorter: method

api:
  security:
    token:
      secret: ${TOKEN_SECRET}