spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sq8OrangeFcamara
    username: adm
    password: adm

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #hibernate.ddl-auto: update
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB







springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    operationsSorter: method

api:
  security:
    token:
      secret: 1234567

accessKey: ${ACCESS_KEY}
secretAccessKey: ${SECRET_KEY}
bucketName: ${BUCKET_NAME}